# Transpose row to columns

In [550]:
import glob
import pandas as pd
import re

In [551]:
path_to_raw_data="H:/IR&A Technical Students/Saumya/IPEDS_03/1. Raw Data"

In [552]:
path =r'H:\IR&A Technical Students\Saumya\IPEDS_03\1. Raw Data\Fall Enrollment'
filenames = glob.glob(path + "/*b_rv.csv")

In [553]:
filenames

['H:\\IR&A Technical Students\\Saumya\\IPEDS_03\\1. Raw Data\\Fall Enrollment\\ef2013b_rv.csv',
 'H:\\IR&A Technical Students\\Saumya\\IPEDS_03\\1. Raw Data\\Fall Enrollment\\ef2014b_rv.csv',
 'H:\\IR&A Technical Students\\Saumya\\IPEDS_03\\1. Raw Data\\Fall Enrollment\\ef2015b_rv.csv',
 'H:\\IR&A Technical Students\\Saumya\\IPEDS_03\\1. Raw Data\\Fall Enrollment\\ef2016b_rv.csv',
 'H:\\IR&A Technical Students\\Saumya\\IPEDS_03\\1. Raw Data\\Fall Enrollment\\ef2017b_rv.csv']

In [554]:
fall_enroll_dict = {re.findall(r'\d+',filenames[i].split('\\')[-1])[0]:pd.read_csv(filenames[i]) for i in range(len(filenames))}

In [555]:
for fileyr, df in fall_enroll_dict.items():
    fall_enroll_dict[fileyr] = df[df["LSTUDY"] == 2].loc[:,~df.columns.str.startswith('X')].drop(["LSTUDY","LINE"],axis=1).set_index("UNITID")

In [556]:
descr = ['_All', '_AgeUnder25', '_AgeUnder18', '_Age18-19', '_Age20-21', '_Age21-24', '_Age25&OverTotal', '_Age25-29', 
         '_Age30-34', '_Age35-39', '_Age40-49', '_Age50-64', '_Age65&over', '_AgeUnknown']
result_dict = {descr[i]: {} for i in range(len(descr))}

In [557]:
fall_enroll_dict['2014']

,EFBAGE,EFAGE01,EFAGE02,EFAGE03,EFAGE04,EFAGE05,EFAGE06,EFAGE07,EFAGE08,EFAGE09
UNITID,,,,,,,,,,
100663,1,3577,4895,1300,1907,8472,3207,4877,6802,11679
100663,2,3144,4456,575,727,7600,1302,3719,5183,8902
100663,3,22,42,6,3,64,9,28,45,73
100663,4,1264,1913,36,36,3177,72,1300,1949,3249
100663,5,1196,1705,154,219,2901,373,1350,1924,3274
100663,6,662,796,379,469,1458,848,1041,1265,2306
100663,7,433,439,725,1180,872,1905,1158,1619,2777
100663,8,265,249,306,419,514,725,571,668,1239
100663,9,100,76,161,225,176,386,261,301,562
100663,10,30,54,97,175,84,272,127,229,356
100663,11,28,43,110,237,71,347,138,280,418
100663,12,10,17,46,122,27,168,56,139,195
100663,13,0,0,5,2,0,7,5,2,7
100690,1,67,92,49,83,159,132,116,175,291
100690,2,12,15,3,7,27,10,15,22,37
100690,4,1,1,0,1,2,1,1,2,3
100690,5,5,6,0,3,11,3,5,9,14
100690,6,6,8,3,3,14,6,9,11,20
100690,7,55,77,46,76,132,122,101,153,254
100690,8,7,22,8,16,29,24,15,38,53
100690,9,17,20,12,17,37,29,29,37,66
100690,10,7,11,9,16,18,25,16,27,43
100690,11,19,15,10,17,34,27,29,32,61
100690,12,5,9,6,8,14,14,11,17,28
100690,13,0,0,1,2,0,3,1,2,3
100724,1,1680,2703,186,243,4383,429,1866,2946,4812
100724,2,1505,2471,120,135,3976,255,1625,2606,4231
100724,3,2,4,1,0,6,1,3,4,7
100724,4,485,904,17,17,1389,34,502,921,1423
100724,5,612,964,38,47,1576,85,650,1011,1661
...,...,...,...,...,...,...,...,...,...,...
485272,7,1,16,0,9,17,9,1,25,26
485272,8,0,7,0,3,7,3,0,10,10
485272,9,0,6,0,2,6,2,0,8,8
485272,10,0,3,0,2,3,2,0,5,5
485272,11,1,0,0,2,1,2,1,2,3
485397,1,5,108,0,0,113,0,5,108,113
485397,2,3,63,0,0,66,0,3,63,66
485397,3,0,1,0,0,1,0,0,1,1
485397,4,0,19,0,0,19,0,0,19,19
485397,5,0,14,0,0,14,0,0,14,14
485397,6,3,29,0,0,32,0,3,29,32
485397,7,2,45,0,0,47,0,2,45,47
485397,8,2,18,0,0,20,0,2,18,20
485397,9,0,15,0,0,15,0,0,15,15
485397,10,0,8,0,0,8,0,0,8,8
485397,11,0,3,0,0,3,0,0,3,3
485397,12,0,1,0,0,1,0,0,1,1
485458,1,215,414,741,1061,629,1802,956,1475,2431
485458,2,127,228,454,703,355,1157,581,931,1512
485458,3,18,43,135,277,61,412,153,320,473
485458,4,38,44,152,201,82,353,190,245,435
485458,5,36,69,83,110,105,193,119,179,298
485458,6,35,72,84,115,107,199,119,187,306
485458,7,88,186,287,358,274,645,375,544,919
485458,8,40,61,86,128,101,214,126,189,315
485458,9,13,33,49,75,46,124,62,108,170
485458,10,10,40,45,38,50,83,55,78,133
485458,11,22,37,52,80,59,132,74,117,191
485458,12,3,14,54,32,17,86,57,46,103
485458,13,0,1,1,5,1,6,1,6,7

In [558]:
inner_dict = {key: None for key in fall_enroll_dict.keys()}

In [559]:
for i in range(len(descr)):
    for fileyr, df in fall_enroll_dict.items():
        inner_dict[fileyr] = df[df['EFBAGE'] == i+1]
    result_dict[descr[i]] = inner_dict

In [560]:
result_dict['_AgeUnknown']['2013']

,EFBAGE,EFAGE01,EFAGE02,EFAGE03,EFAGE04,EFAGE05,EFAGE06,EFAGE07,EFAGE08,EFAGE09
UNITID,,,,,,,,,,
100654,14,0,1,0,0,1,0,0,1,1
100663,14,0,0,0,90,0,90,0,90,90
100690,14,0,2,0,5,2,5,0,7,7
100760,14,39,29,0,0,68,0,39,29,68
100830,14,0,0,4,8,0,12,4,8,12
101073,14,0,0,3,4,0,7,3,4,7
101453,14,1,0,0,1,1,1,1,1,2
101505,14,0,0,0,1,0,1,0,1,1
101514,14,5,0,2,3,5,5,7,3,10
101693,14,0,0,0,10,0,10,0,10,10
101912,14,6,13,0,3,19,3,6,16,22
102058,14,5,0,0,0,5,0,5,0,5
102067,14,6,5,4,4,11,8,10,9,19
102270,14,2,1,3,1,3,4,5,2,7
102368,14,1,0,2,0,1,2,3,0,3
102377,14,4,12,1,0,16,1,5,12,17
102395,14,0,0,1,1,0,2,1,1,2
102553,14,0,0,1,0,0,1,1,0,1
102614,14,0,0,2,3,0,5,2,3,5
102669,14,0,3,0,0,3,0,0,3,3
103361,14,0,0,1,0,0,1,1,0,1
103893,14,0,1,0,0,1,0,0,1,1
104151,14,2,0,0,0,2,0,2,0,2
104160,14,0,0,1,0,0,1,1,0,1
104391,14,0,1,0,0,1,0,0,1,1
104577,14,0,1,0,0,1,0,0,1,1
104708,14,0,0,5,0,0,5,5,0,5
105145,14,0,0,3,2,0,5,3,2,5
105154,14,0,0,7,4,0,11,7,4,11
105163,14,1,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
480356,14,1,0,0,0,1,0,1,0,1
480718,14,0,0,80,23,0,103,80,23,103
480727,14,11,0,0,0,11,0,11,0,11
480736,14,1,2,1,1,3,2,2,3,5
480754,14,0,0,0,1,0,1,0,1,1
480994,14,0,0,0,1,0,1,0,1,1
481003,14,1,0,0,0,1,0,1,0,1
481100,14,0,0,1,0,0,1,1,0,1
481119,14,5,15,0,0,20,0,5,15,20
481137,14,2,1,0,0,3,0,2,1,3
481191,14,14,17,0,0,31,0,14,17,31
481207,14,1,2,0,0,3,0,1,2,3
481234,14,63,69,0,0,132,0,63,69,132
481243,14,0,0,1,5,0,6,1,5,6
481298,14,0,1,0,0,1,0,0,1,1
481313,14,1,0,0,0,1,0,1,0,1
481322,14,0,1,0,2,1,2,0,3,3
481340,14,0,6,0,0,6,0,0,6,6
481571,14,0,1,0,0,1,0,0,1,1
481580,14,0,0,0,1,0,1,0,1,1
481623,14,1,0,0,0,1,0,1,0,1
482033,14,0,1,0,0,1,0,0,1,1
482097,14,12,11,0,0,23,0,12,11,23
482398,14,1,0,0,0,1,0,1,0,1
482705,14,0,0,5,8,0,13,5,8,13
482857,14,557,0,70,48,557,118,627,48,675
483018,14,5,0,0,0,5,0,5,0,5
483036,14,0,0,1,1,0,2,1,1,2
483054,14,1,0,0,0,1,0,1,0,1
483212,14,0,1,0,0,1,0,0,1,1

In [561]:
# for descr, inner_dict in result_dict.items():
#     for yr in inner_dict.keys():
# #         df.rename(columns={str(col):str(col)+ descr +'_'+str(yr) for col in df.columns})
#         inner_dict[yr].columns=inner_dict[yr].columns+descr+'_'+str(yr)
# #         col_names={str(col):str(col)+ descr +'_'+str(yr) for col in df.columns}
# #         df.columns=[str(col)+ descr +'_'+str(yr) for col in df.columns]
# #     print(col_names)

In [548]:
for yr , df in result_dict['_All'].items():
    result_dict['_All'][yr].columns=result_dict['_All'][yr].columns+'_All'+'_'+str(yr)
#     print(df.columns)
#     df.columns=df.columns+'_All'+'_'+str(yr)
# #     print(df)
# #     print(result_dict['_All'][yr])

In [549]:
result_dict['_AgeUnknown']['2013']

,EFBAGE_All_2013_All_2013,EFAGE01_All_2013_All_2013,EFAGE02_All_2013_All_2013,EFAGE03_All_2013_All_2013,EFAGE04_All_2013_All_2013,EFAGE05_All_2013_All_2013,EFAGE06_All_2013_All_2013,EFAGE07_All_2013_All_2013,EFAGE08_All_2013_All_2013,EFAGE09 _All_2013_All_2013
UNITID,,,,,,,,,,
100654,14,0,1,0,0,1,0,0,1,1
100663,14,0,0,0,90,0,90,0,90,90
100690,14,0,2,0,5,2,5,0,7,7
100760,14,39,29,0,0,68,0,39,29,68
100830,14,0,0,4,8,0,12,4,8,12
101073,14,0,0,3,4,0,7,3,4,7
101453,14,1,0,0,1,1,1,1,1,2
101505,14,0,0,0,1,0,1,0,1,1
101514,14,5,0,2,3,5,5,7,3,10
101693,14,0,0,0,10,0,10,0,10,10
101912,14,6,13,0,3,19,3,6,16,22
102058,14,5,0,0,0,5,0,5,0,5
102067,14,6,5,4,4,11,8,10,9,19
102270,14,2,1,3,1,3,4,5,2,7
102368,14,1,0,2,0,1,2,3,0,3
102377,14,4,12,1,0,16,1,5,12,17
102395,14,0,0,1,1,0,2,1,1,2
102553,14,0,0,1,0,0,1,1,0,1
102614,14,0,0,2,3,0,5,2,3,5
102669,14,0,3,0,0,3,0,0,3,3
103361,14,0,0,1,0,0,1,1,0,1
103893,14,0,1,0,0,1,0,0,1,1
104151,14,2,0,0,0,2,0,2,0,2
104160,14,0,0,1,0,0,1,1,0,1
104391,14,0,1,0,0,1,0,0,1,1
104577,14,0,1,0,0,1,0,0,1,1
104708,14,0,0,5,0,0,5,5,0,5
105145,14,0,0,3,2,0,5,3,2,5
105154,14,0,0,7,4,0,11,7,4,11
105163,14,1,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
480356,14,1,0,0,0,1,0,1,0,1
480718,14,0,0,80,23,0,103,80,23,103
480727,14,11,0,0,0,11,0,11,0,11
480736,14,1,2,1,1,3,2,2,3,5
480754,14,0,0,0,1,0,1,0,1,1
480994,14,0,0,0,1,0,1,0,1,1
481003,14,1,0,0,0,1,0,1,0,1
481100,14,0,0,1,0,0,1,1,0,1
481119,14,5,15,0,0,20,0,5,15,20
481137,14,2,1,0,0,3,0,2,1,3
481191,14,14,17,0,0,31,0,14,17,31
481207,14,1,2,0,0,3,0,1,2,3
481234,14,63,69,0,0,132,0,63,69,132
481243,14,0,0,1,5,0,6,1,5,6
481298,14,0,1,0,0,1,0,0,1,1
481313,14,1,0,0,0,1,0,1,0,1
481322,14,0,1,0,2,1,2,0,3,3
481340,14,0,6,0,0,6,0,0,6,6
481571,14,0,1,0,0,1,0,0,1,1
481580,14,0,0,0,1,0,1,0,1,1
481623,14,1,0,0,0,1,0,1,0,1
482033,14,0,1,0,0,1,0,0,1,1
482097,14,12,11,0,0,23,0,12,11,23
482398,14,1,0,0,0,1,0,1,0,1
482705,14,0,0,5,8,0,13,5,8,13
482857,14,557,0,70,48,557,118,627,48,675
483018,14,5,0,0,0,5,0,5,0,5
483036,14,0,0,1,1,0,2,1,1,2
483054,14,1,0,0,0,1,0,1,0,1
483212,14,0,1,0,0,1,0,0,1,1

In [426]:
des

'_AgeUnknown'

In [161]:
inner_dict.keys()

dict_keys(['2017'])

In [23]:
# df

# list_df = []

# for i in range(1,15):
#     list_df.append(df[df['EFBAGE'] == i])

descr = ['_All', '_AgeUnder25', '_AgeUnder18', '_Age18-19', '_Age20-21', '_Age21-24', '_Age25&OverTotal', '_Age25-29', 
         '_Age30-34', '_Age35-39', '_Age40-49', '_Age50-64', '_Age65&over', '_AgeUnknown']

for i in range(0,14):
    list_df[i].columns = [str(col) + descr[i]  for col in list_df[i].columns]

In [33]:
final = pd.concat(list_df, axis=1)

In [34]:
final

,EFBAGE_All,EFAGE01_All,EFAGE02_All,EFAGE03_All,EFAGE04_All,EFAGE05_All,EFAGE06_All,EFAGE07_All,EFAGE08_All,EFAGE09 _All,...,EFBAGE_AgeUnknown,EFAGE01_AgeUnknown,EFAGE02_AgeUnknown,EFAGE03_AgeUnknown,EFAGE04_AgeUnknown,EFAGE05_AgeUnknown,EFAGE06_AgeUnknown,EFAGE07_AgeUnknown,EFAGE08_AgeUnknown,EFAGE09 _AgeUnknown
UNITID,,,,,,,,,,,,,,,,,,,,,
100690,1,57,78,58,101,135,159,115,179,294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100724,1,1647,2721,140,219,4368,359,1787,2940,4727,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100751,1,13135,16085,1316,2027,29220,3343,14451,18112,32563,...,14.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
100760,1,412,525,357,475,937,832,769,1000,1769,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100830,1,1086,2009,433,745,3095,1178,1519,2754,4273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100858,1,10129,10267,1484,778,20396,2262,11613,11045,22658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101028,1,388,476,216,448,864,664,604,924,1528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101143,1,453,404,458,440,857,898,911,844,1755,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101161,1,1002,1551,804,1424,2553,2228,1806,2975,4781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101189,1,741,1038,287,517,1779,804,1028,1555,2583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101240,1,1165,1348,918,1678,2513,2596,2083,3026,5109,...,14.0,0.0,0.0,7.0,0.0,0.0,7.0,7.0,0.0,7.0
101286,1,771,1212,777,1783,1983,2560,1548,2995,4543,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101295,1,1150,1553,929,1813,2703,2742,2079,3366,5445,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101301,1,408,499,168,543,907,711,576,1042,1618,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101435,1,505,376,82,185,881,267,587,561,1148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101462,1,204,251,184,190,455,374,388,441,829,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101471,1,282,103,51,10,385,61,333,113,446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101480,1,2432,3048,823,1258,5480,2081,3255,4306,7561,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101499,1,290,258,154,298,548,452,444,556,1000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101505,1,1170,1629,2303,3836,2799,6139,3473,5465,8938,...,14.0,0.0,0.0,4.0,4.0,0.0,8.0,4.0,4.0,8.0
101514,1,1801,1761,2819,3519,3562,6338,4620,5280,9900,...,14.0,0.0,0.0,13.0,0.0,0.0,13.0,13.0,0.0,13.0
101569,1,800,895,542,891,1695,1433,1342,1786,3128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101602,1,422,613,319,388,1035,707,741,1001,1742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101648,1,330,91,3,1,421,4,333,92,425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101709,1,689,1489,84,147,2178,231,773,1636,2409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101736,1,684,892,916,1260,1576,2176,1600,2152,3752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101897,1,505,697,509,902,1202,1411,1014,1599,2613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101912,1,681,945,38,76,1626,114,719,1021,1740,...,14.0,0.0,0.0,4.0,14.0,0.0,18.0,4.0,14.0,18.0
101949,1,368,424,255,315,792,570,623,739,1362,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101994,1,90,115,99,185,205,284,189,300,489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486983,1,1,45,0,0,46,0,1,45,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487010,1,30,233,2,22,263,24,32,255,287,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487092,1,403,573,2,0,976,2,405,573,978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487162,1,341,823,896,1461,1164,2357,1237,2284,3521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487250,1,7,1,0,0,8,0,7,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487296,1,89,103,80,106,192,186,169,209,378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487320,1,3946,1346,4511,3446,5292,7957,8457,4792,13249,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487375,1,15,149,15,148,164,163,30,297,327,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487667,1,68,63,13,45,131,58,81,108,189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487676,1,3,164,0,0,167,0,3,164,167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487791,1,106,6,67,3,112,70,173,9,182,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487922,1,0,37,2,23,37,25,2,60,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488022,1,19,4,14,4,23,18,33,8,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488253,1,51,24,0,0,75,0,51,24,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488305,1,49,49,3,1,98,4,52,50,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488411,1,1,45,0,0,46,0,1,45,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488730,1,258,260,1236,1730,518,2966,1494,1990,3484,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488819,1,29,31,0,0,60,0,29,31,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488916,1,1,16,0,0,17,0,1,16,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488943,1,203,202,0,0,405,0,203,202,405,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488989,1,8,90,0,0,98,0,8,90,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488998,1,4,79,0,0,83,0,4,79,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489104,1,6,4,46,18,10,64,52,22,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489201,1,1000,1035,1928,2721,2035,4649,2928,3756,6684,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489256,1,196,28,4,0,224,4,200,28,228,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489344,1,5,45,0,40,50,40,5,85,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489353,1,5,22,6,26,27,32,11,48,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489779,1,4,49,65,355,53,420,69,404,473,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489788,1,8,24,56,266,32,322,64,290,354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489937,1,103,73,70,49,176,119,173,122,295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
final=final.add_suffix('_2016')

In [43]:
final

,EFBAGE_All_2016,EFAGE01_All_2016,EFAGE02_All_2016,EFAGE03_All_2016,EFAGE04_All_2016,EFAGE05_All_2016,EFAGE06_All_2016,EFAGE07_All_2016,EFAGE08_All_2016,EFAGE09 _All_2016,...,EFBAGE_AgeUnknown_2016,EFAGE01_AgeUnknown_2016,EFAGE02_AgeUnknown_2016,EFAGE03_AgeUnknown_2016,EFAGE04_AgeUnknown_2016,EFAGE05_AgeUnknown_2016,EFAGE06_AgeUnknown_2016,EFAGE07_AgeUnknown_2016,EFAGE08_AgeUnknown_2016,EFAGE09 _AgeUnknown_2016
UNITID,,,,,,,,,,,,,,,,,,,,,
100690,1,57,78,58,101,135,159,115,179,294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100724,1,1647,2721,140,219,4368,359,1787,2940,4727,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100751,1,13135,16085,1316,2027,29220,3343,14451,18112,32563,...,14.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
100760,1,412,525,357,475,937,832,769,1000,1769,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100830,1,1086,2009,433,745,3095,1178,1519,2754,4273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100858,1,10129,10267,1484,778,20396,2262,11613,11045,22658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101028,1,388,476,216,448,864,664,604,924,1528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101143,1,453,404,458,440,857,898,911,844,1755,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101161,1,1002,1551,804,1424,2553,2228,1806,2975,4781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101189,1,741,1038,287,517,1779,804,1028,1555,2583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101240,1,1165,1348,918,1678,2513,2596,2083,3026,5109,...,14.0,0.0,0.0,7.0,0.0,0.0,7.0,7.0,0.0,7.0
101286,1,771,1212,777,1783,1983,2560,1548,2995,4543,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101295,1,1150,1553,929,1813,2703,2742,2079,3366,5445,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101301,1,408,499,168,543,907,711,576,1042,1618,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101435,1,505,376,82,185,881,267,587,561,1148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101462,1,204,251,184,190,455,374,388,441,829,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101471,1,282,103,51,10,385,61,333,113,446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101480,1,2432,3048,823,1258,5480,2081,3255,4306,7561,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101499,1,290,258,154,298,548,452,444,556,1000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101505,1,1170,1629,2303,3836,2799,6139,3473,5465,8938,...,14.0,0.0,0.0,4.0,4.0,0.0,8.0,4.0,4.0,8.0
101514,1,1801,1761,2819,3519,3562,6338,4620,5280,9900,...,14.0,0.0,0.0,13.0,0.0,0.0,13.0,13.0,0.0,13.0
101569,1,800,895,542,891,1695,1433,1342,1786,3128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101602,1,422,613,319,388,1035,707,741,1001,1742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101648,1,330,91,3,1,421,4,333,92,425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101709,1,689,1489,84,147,2178,231,773,1636,2409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101736,1,684,892,916,1260,1576,2176,1600,2152,3752,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101897,1,505,697,509,902,1202,1411,1014,1599,2613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101912,1,681,945,38,76,1626,114,719,1021,1740,...,14.0,0.0,0.0,4.0,14.0,0.0,18.0,4.0,14.0,18.0
101949,1,368,424,255,315,792,570,623,739,1362,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101994,1,90,115,99,185,205,284,189,300,489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486983,1,1,45,0,0,46,0,1,45,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487010,1,30,233,2,22,263,24,32,255,287,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487092,1,403,573,2,0,976,2,405,573,978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487162,1,341,823,896,1461,1164,2357,1237,2284,3521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487250,1,7,1,0,0,8,0,7,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487296,1,89,103,80,106,192,186,169,209,378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487320,1,3946,1346,4511,3446,5292,7957,8457,4792,13249,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487375,1,15,149,15,148,164,163,30,297,327,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487667,1,68,63,13,45,131,58,81,108,189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487676,1,3,164,0,0,167,0,3,164,167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487791,1,106,6,67,3,112,70,173,9,182,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487922,1,0,37,2,23,37,25,2,60,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488022,1,19,4,14,4,23,18,33,8,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488253,1,51,24,0,0,75,0,51,24,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488305,1,49,49,3,1,98,4,52,50,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488411,1,1,45,0,0,46,0,1,45,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488730,1,258,260,1236,1730,518,2966,1494,1990,3484,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488819,1,29,31,0,0,60,0,29,31,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488916,1,1,16,0,0,17,0,1,16,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488943,1,203,202,0,0,405,0,203,202,405,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488989,1,8,90,0,0,98,0,8,90,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488998,1,4,79,0,0,83,0,4,79,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489104,1,6,4,46,18,10,64,52,22,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489201,1,1000,1035,1928,2721,2035,4649,2928,3756,6684,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489256,1,196,28,4,0,224,4,200,28,228,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489344,1,5,45,0,40,50,40,5,85,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489353,1,5,22,6,26,27,32,11,48,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489779,1,4,49,65,355,53,420,69,404,473,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489788,1,8,24,56,266,32,322,64,290,354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489937,1,103,73,70,49,176,119,173,122,295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN